version: '3'

services:
    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: demo
            MYSQL_USER: demo
            MYSQL_PASSWORD: secret
        ports:
            - '33060:3306'
